version: '2'

services:
  backend:
    command: ["node", "./js/index.js"]
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
    - .:/usr/src
    ports:
    - "3000:3000"
    expose:
    - "3000"
    depends_on:
    - postgres
    environment:
      DATABASE_URL: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
