version: '2'

services:
  backend:
    command: ["npm", "run", "start.prod"]
    environment:
      NODE_ENV: production
      LOGGING_LEVEL: info
      # TODO: Set as production origin
      ALLOWED_ORIGIN